-- Noite de Gratidão (Juan, 19/10 às 18h) — inscrições pelo site
-- Projeto Supabase: CRM Vitalício (lffzxqwgqgsiumunahyt)
-- Este arquivo reúne, na ordem, tudo que foi aplicado no banco.

create extension if not exists pg_net with schema extensions;

-- 1. Tabela
create table if not exists public.inscricoes_aniversario_juan (
  id uuid primary key default gen_random_uuid(),
  numero integer generated by default as identity,
  nome text not null check (char_length(nome) between 2 and 120),
  email text check (email is null or (char_length(email) <= 160 and email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$')),
  telefone text check (telefone is null or char_length(telefone) <= 30),
  acompanhantes smallint not null default 0 check (acompanhantes between 0 and 10),
  recado text check (recado is null or char_length(recado) <= 500),
  origem text not null default 'link',
  criado_em timestamptz not null default now()
);
create index if not exists inscricoes_aniversario_juan_criado_em_idx on public.inscricoes_aniversario_juan (criado_em desc);
create unique index if not exists inscricoes_aniversario_juan_numero_idx on public.inscricoes_aniversario_juan (numero);

-- 2. Segurança: site só insere (via RPC); só usuário logado lê; chave de serviço tudo.
alter table public.inscricoes_aniversario_juan enable row level security;
create policy "convidados_podem_se_inscrever" on public.inscricoes_aniversario_juan for insert to anon with check (true);
create policy "logados_veem_inscricoes" on public.inscricoes_aniversario_juan for select to authenticated using (true);
grant usage on schema public to anon, authenticated, service_role;
grant insert on public.inscricoes_aniversario_juan to anon;
grant select on public.inscricoes_aniversario_juan to authenticated;
grant select, insert, update, delete on public.inscricoes_aniversario_juan to service_role;

-- 3. RPC usada pelo formulário: insere e devolve o número da inscrição.
create or replace function public.inscrever_aniversario_juan(
  p_nome text, p_telefone text default null, p_acompanhantes int default 0, p_recado text default null, p_email text default null
) returns json
language plpgsql security definer set search_path = public as $$
declare r record;
begin
  insert into public.inscricoes_aniversario_juan (nome, telefone, acompanhantes, recado, email)
  values (btrim(p_nome), nullif(btrim(p_telefone), ''), coalesce(p_acompanhantes, 0), nullif(btrim(p_recado), ''), lower(nullif(btrim(p_email), '')))
  returning id, numero, nome, acompanhantes into r;
  return json_build_object('id', r.id, 'numero', r.numero, 'nome', r.nome, 'acompanhantes', r.acompanhantes);
end;
$$;
revoke all on function public.inscrever_aniversario_juan(text, text, int, text, text) from public;
grant execute on function public.inscrever_aniversario_juan(text, text, int, text, text) to anon, authenticated;

-- 4. Segredos no Vault (valores cadastrados pelo painel/SQL, não ficam neste arquivo):
--    BREVO_API_KEY, NOTIFY_FROM_EMAIL (altaimpactoprojetos@gmail.com), NOTIFY_FROM_NAME (opcional)
create or replace function public.segredo_evento(nome_segredo text)
returns text language sql security definer set search_path = vault, public as $$
  select decrypted_secret from vault.decrypted_secrets where name = nome_segredo limit 1;
$$;
revoke all on function public.segredo_evento(text) from public, anon, authenticated;
grant execute on function public.segredo_evento(text) to service_role;

-- 5. Gatilho: a cada inscrição chama a Edge Function notificar-inscricao (e-mail ao convidado).
--    O token abaixo é a chave pública (anon) do projeto, exigida pela função (verify_jwt).
create or replace function public.notificar_inscricao_aniversario_juan()
returns trigger language plpgsql security definer set search_path = public, extensions as $$
begin
  perform net.http_post(
    url := 'https://lffzxqwgqgsiumunahyt.supabase.co/functions/v1/notificar-inscricao',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZnp4cXdncWdzaXVtdW5haHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4OTU3NDUsImV4cCI6MjEwNDQ3MTc0NX0.7d8SAWdLCarGRdY5uwb5OrpDY7sPHHN4mDe8ZJsFVZw'
    ),
    body := jsonb_build_object('id', new.id, 'record', to_jsonb(new)),
    timeout_milliseconds := 8000
  );
  return new;
end;
$$;
drop trigger if exists trg_notificar_inscricao_aniversario_juan on public.inscricoes_aniversario_juan;
create trigger trg_notificar_inscricao_aniversario_juan
  after insert on public.inscricoes_aniversario_juan
  for each row execute function public.notificar_inscricao_aniversario_juan();
